### ISSUE TITLE
Pre-defined size of PRs

### ISSUE THREAD

**Issue by hadilq** [pascalgn/size-label-action#11]
The current definition of sizes are as 
```
const sizes = {
  0: "XS",
  10: "S",
  30: "M",
  100: "L",
  500: "XL",
  1000: "XXL"
};
```
However it's possible to define `SIZES` in yaml file and then parse them from `process.env.SIZES`. Would be nice to have this feature. Thank you.

**Comment by pascalgn** [comment]
I think this could be useful. Would you like to create a PR for this?

**Comment by hadilq** [comment]
Sure! But it will take some time to open a window to work on it ;)
