### ISSUE TITLE
Consider the option to ommit deleted files count 

### ISSUE THREAD

**Issue by tonthanhhung** [pascalgn/size-label-action#13]
In my project, there is a strict rule about the size of PR, Which if it's bigger then XXL, it won't have PR's approval,
Practically, some of the big files deletion (refactoring) is counted in the labeling action which is a bit unfair to be counted while no body care about the deleted files much, or just 2 seconds for reviewing (means they should not be considered in review effort)
Is it make sense to have option to not consider file deletion count ?

**Comment by pascalgn** [comment]
I don't think it would be good to have it as default behaviour, but having an option for it would be OK, I think. Do you want to provide a PR for it? 🙏

**Comment by pascalgn** [comment]
It's a long time since there was some activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen it!
