### ISSUE TITLE
Possibility to ignore commits

### ISSUE THREAD

**Issue by levsa** [pascalgn/size-label-action#20]
It would be nice to be able to ignore commits based on a pattern that matches the commit message, to exclude automatic reformatting of files from size calculation. Useful when files are automatically reformatted and committed separately so they can be skipped over during review.

**Comment by pascalgn** [comment]
While this is certainly possible, it's not too easy to do: currently, we just need to call one API endpoint, which gives us the diff: https://github.com/pascalgn/size-label-action/blob/master/index.js#L64 What you're proposing would require us to go over each commit (ignoring specific ones based on e.g. commit message) and then build the full diff based on the list of commits. This can get quite complicated, for example when ignored and included commits both change the same file.

My suggestion would be to fork this action and implement the required changes in the fork. If you want, you can also try to create a PR in this repository, but I'm not sure if it will be merged, this will probably depend on PR size and how much complexity it adds.

I will close this for now, but feel free to re-open! 👍
