### ISSUE TITLE
Convert to pure JavaScript Action?

### ISSUE THREAD

**Issue by davidparsson** [pascalgn/size-label-action#21]
Hi, and thanks for the action!

Is there any specific reason for this not being a pure JavaScript action? They're faster, and implementing that seems rather simple.

**Comment by pascalgn** [comment]
This request seems familiar... https://github.com/pascalgn/automerge-action/issues/125 😄 

Same answer here: feel free to create a PR for it! 👍

**Comment by davidparsson** [comment]
Sorry, I only looked at the open issues before posting. Thanks!
