### ISSUE TITLE
Add support for HTTPS proxy

### ISSUE THREAD

**Issue by donovanmuller** [pascalgn/size-label-action#27]
For the unlucky teams in a corporate environment, where all API requests have to go through a HTTPS proxy, with the action run on self-hosted runners, unfortunately this action does not work as it does not support a proxy agent.

It would great to add HTTPS proxy support to solve for this use case.

**Comment by casr-anz** [comment]
I'm seeing the same issue too, so would really appreciate this issue being fixed!

**Comment by brianpaden289** [comment]
Same, I get HTTP 500 timeouts.

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
