### ISSUE TITLE
Multiple github checks created

### ISSUE THREAD

**Issue by steebchen** [pascalgn/size-label-action#3]
If a PR event is sent, is it possible to re-use the first check? instead of creating new checks? Note the "assign size labels" checks:

![Selection_999(1130)](https://user-images.githubusercontent.com/5013932/54478030-28a2a300-480e-11e9-972c-6d6a666fcc59.jpg)

**Comment by pascalgn** [comment]
I know what you mean and I also find it annoying, but as far as I know, there is no way to control this: GitHub will just display a state for each action run that was executed. See for example the [official docker action](https://github.com/actions/docker/blob/master/cli/entrypoint.sh), it just executes the `docker` command and returns an exit code. GitHub will control how these checks are displayed.

However, if you know of a way to control this, I would be happy to implement it :)

**Comment by steebchen** [comment]
Alright, thanks for the info. :) I'll close this for now since it seems not configurable at the moment.
