### ISSUE TITLE
Resource not accessible by integration - Pull request opened by dependabot

### ISSUE THREAD

**Issue by guibranco** [pascalgn/size-label-action#32]
Hello, I'm running this action on a private internal repository, for a enterprise account, and I'm getting this output when the pull request was opened by `dependabot` 

![image](https://user-images.githubusercontent.com/3362854/192772379-7689debb-7418-4264-8aba-39500a764820.png)

When a real user opens the PR, the action runs sucessfully, is there anything that we can do to allow this action run on this scenario ?

**Comment by pascalgn** [comment]
I'm not sure this will work, but can you try going to the repository action settings, e.g. https://github.com/your-organization/your-repository/settings/actions and enabling this?

## Please note that this can have serious security implications (e.g. people being able to create PRs can extract action secrets and use them to access the repository) so make sure it is okay for your situation

<img width="688" alt="image" src="https://user-images.githubusercontent.com/432333/194644854-83f0b7d4-29e3-4351-a346-240ae8f63ba3.png">
