### ISSUE TITLE
Node.js 16 is deprecated

### ISSUE THREAD

**Issue by dione-kist-jemmic** [pascalgn/size-label-action#47]
The action is using node 16 deprecated version. I create the #46 to upgrade to node 20 and solve issue below:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pascalgn/size-label-action@v0.5.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by pascalgn** [comment]
Thanks for raising the issue and creating the PR! The PR is merged now and it's released as `pascalgn/size-label-action@v0.5.1` 🚀
